language: go
go_import_path: go-hep.org/x/hep
go:
  - 1.6
  - 1.7
  - 1.8
  - tip

sudo: false

notifications:
  email:
    recipients:
      - binet@cern.ch
    on_success: change
    on_failure: always

